### ISSUE TITLE
Dim background images

### ISSUE THREAD

**Issue by kristjanjansen** [kuressaareametikool/stuff#33]
### Plan A

fshfusdhfjhsdkjfjksehf

``` css
.pulpfiction {
    background-image: gradient, 
}
```
